import React from 'react';
import { SitePhase } from '../../../hooks/useSiteState';
import { projects as projectsData } from '../../../data/projects';

interface ProjectsRoomProps {
  navigateTo: (phase: SitePhase) => void;
}

interface Project {
  name: string;
  description: string;
  color: string;
  url: string;
  cta: string;
  slug: string;
}

const toSlug = (name: string) =>
  name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const projects: Project[] = projectsData.map(p => ({
  name: p.name,
  description: p.description,
  color: p.color,
  url: p.liveUrl,
  cta: p.actionText,
  slug: toSlug(p.name),
}));

// Suppress unused variable warning — projects data is used for URL references
void projects;

const ProjectsRoom: React.FC<ProjectsRoomProps> = ({ navigateTo }) => {
  return (
    <div className="projects-room">
      <style>{mainStyles}</style>

      {/* ── NAV ── */}
      <nav className="proj-nav">
        <button className="proj-nav-link" onClick={() => navigateTo('lobby')}>
          ← Lobby
        </button>
        <div className="proj-nav-right">
          <button className="proj-nav-link" onClick={() => navigateTo('about')}>About</button>
          <button className="proj-nav-link active">Projects</button>
        </div>
      </nav>

      {/* ── HERO ── */}
      <section className="proj-hero">
        <p className="proj-hero-label">Selected Works</p>
        <h1 className="proj-hero-title">Things I've Built</h1>
        <p className="proj-hero-subtitle">
          Games, tools, and the occasional questionable decision.
          Each card was generated by its own <span className="proj-gemini-tag">Gemini 3 Pro</span> subagent.
        </p>
      </section>

      {/* ── PROJECT CARDS ── */}
      <section className="proj-gallery">
        {renderInfiniteLevelsCard()}
        {renderFourNinesCard()}
        {renderMatchFiveCard()}
        {renderSurvivorStatsCard()}
        {renderPlantGuruCard()}
      </section>

      {/* ── FOOTER NAV ── */}
      <footer className="proj-footer">
        <button className="proj-footer-link" onClick={() => navigateTo('about')}>
          ← Back to About
        </button>
        <button className="proj-footer-link" onClick={() => navigateTo('lobby')}>
          Lobby →
        </button>
      </footer>

      <style>{cardStyles}</style>
    </div>
  );
};

// ══════════════════════════════════════════════════════════════════════════════
// CARD 1: INFINITE LEVELS — Dark academia chalkboard
// Handwritten chalk equations, recursive boxes, dusty green slate
// ══════════════════════════════════════════════════════════════════════════════

function renderInfiniteLevelsCard() {
  return (
    <a href="https://hamburgj.github.io/Infinite-Levels/" target="_blank" rel="noopener noreferrer" className="card-link">
      <div className="card-chalk">
        <div className="chalk-dust" />
        <div className="chalk-grid" />
        <div className="chalk-recursion">
          <div className="chalk-box">
            <div className="chalk-box">
              <div className="chalk-box">
                <div className="chalk-box-inner" />
              </div>
            </div>
          </div>
        </div>
        <div className="chalk-equations">
          <span className="chalk-eq eq1">∞ + 1 = ∞</span>
          <span className="chalk-eq eq2">lim n→∞</span>
          <span className="chalk-eq eq3">ℵ₀ &lt; ℵ₁</span>
          <span className="chalk-eq eq4">∑ᵢ₌₁ⁿ</span>
          <span className="chalk-eq eq5">∀ε &gt; 0</span>
        </div>
        <div className="chalk-content">
          <div className="chalk-subtitle">level ∞ / ∞</div>
          <h2 className="chalk-title">Infinite Levels!</h2>
          <p className="chalk-desc">
            A recursive descent into mathematical madness. Every level you beat reveals
            another level. There is no end. There is no beginning.
          </p>
          <span className="chalk-cta">Descend Forever →</span>
        </div>
        <div className="card-agent-badge">gemini-3-pro / subagent-chalk</div>
      </div>
    </a>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// CARD 2: FOUR NINES — Retro green CRT terminal
// Scanlines, phosphor glow, blinking cursor, LED digits
// ══════════════════════════════════════════════════════════════════════════════

function renderFourNinesCard() {
  return (
    <a href="https://hamburgj.github.io/four-nines-game/" target="_blank" rel="noopener noreferrer" className="card-link">
      <div className="card-crt">
        <div className="crt-scanlines" />
        <div className="crt-vignette" />
        <div className="crt-screen">
          <div className="crt-header">
            <div className="crt-digits">
              <span className="crt-digit">9</span>
              <span className="crt-digit">9</span>
              <span className="crt-digit">9</span>
              <span className="crt-digit">9</span>
            </div>
            <div className="crt-equations">
              9 + 9 - 9 - 9 = 0<br/>
              9 / 9 + 9 - 9 = 1<br/>
              9 / 9 + 9 / 9 = 2<br/>
              (9 + 9 + 9) / 9 = 3
            </div>
          </div>
          <div className="crt-title">FOUR NINES<span className="crt-cursor">_</span></div>
          <div className="crt-version">daily math terminal v9.9.9.9</div>
          <p className="crt-desc">
            <span className="crt-prompt">&gt;</span> You have exactly four 9s. Combine them with
            any operation known to mathematics. Hit the target. Keep the streak.
          </p>
          <span className="crt-cta">./play --today</span>
        </div>
        <div className="crt-statusbar">
          <span><span className="crt-dot" />CONNECTED</span>
          <span>STREAK: ∞</span>
          <span>9 × 9 × 9 × 9</span>
        </div>
        <div className="card-agent-badge crt-agent">gemini-3-pro / subagent-terminal</div>
      </div>
    </a>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// CARD 3: MATCH FIVE — Ultra-clean Swiss/minimalist design
// Helvetica, massive whitespace, hairline rules, brutal grid
// ══════════════════════════════════════════════════════════════════════════════

function renderMatchFiveCard() {
  return (
    <a href="https://hamburgj.github.io/match-five/" target="_blank" rel="noopener noreferrer" className="card-link">
      <div className="card-swiss">
        <div className="swiss-rule swiss-rule-top" />
        <div className="swiss-rule swiss-rule-mid" />
        <div className="swiss-grid">
          <div className="swiss-col swiss-col-left">
            <span className="swiss-num">05</span>
            <div className="swiss-tiles">
              <span className="swiss-tile">M</span>
              <span className="swiss-tile">A</span>
              <span className="swiss-tile">T</span>
              <span className="swiss-tile">C</span>
              <span className="swiss-tile">H</span>
            </div>
          </div>
          <div className="swiss-col swiss-col-right">
            <span className="swiss-category">WORD PUZZLE</span>
            <h2 className="swiss-title">Match<br/>Five</h2>
            <p className="swiss-desc">
              One word. Five meanings. A clean, precise puzzle where vocabulary
              meets lateral thinking. No clutter. No noise. Just words.
            </p>
            <span className="swiss-cta">Play →</span>
          </div>
        </div>
        <div className="swiss-footer">
          <span>DAILY</span>
          <span>•</span>
          <span>WORDS</span>
          <span>•</span>
          <span>MEANING</span>
        </div>
        <div className="card-agent-badge swiss-agent">gemini-3-pro / subagent-minimal</div>
      </div>
    </a>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// CARD 4: SURVIVOR STATS — Tribal council inferno
// Fire gradient, rising embers, parchment vote card, dramatic
// ══════════════════════════════════════════════════════════════════════════════

function renderSurvivorStatsCard() {
  return (
    <a href="https://hamburgj.github.io/survivor-stats/" target="_blank" rel="noopener noreferrer" className="card-link">
      <div className="card-tribal">
        <div className="tribal-fire" />
        <div className="tribal-embers">
          {Array.from({ length: 14 }).map((_, i) => <span key={i} className="tribal-ember" />)}
        </div>
        <div className="tribal-torches" />
        <div className="tribal-pattern" />
        <div className="tribal-smoke" />
        <div className="tribal-vote">
          <span className="tribal-vote-label">VOTE</span>
          <span className="tribal-vote-name">Jeff</span>
        </div>
        <div className="tribal-stats">
          <div className="tribal-stat">
            <span className="tribal-stat-num">47+</span>
            <span className="tribal-stat-label">Seasons</span>
          </div>
          <div className="tribal-stat">
            <span className="tribal-stat-num">800+</span>
            <span className="tribal-stat-label">Castaways</span>
          </div>
        </div>
        <div className="tribal-content">
          <div className="tribal-divider" />
          <span className="tribal-eyebrow">Tribal Council Analytics</span>
          <h2 className="tribal-title">Survivor Stats</h2>
          <p className="tribal-desc">
            The tribe has spoken — and it said "give me a database." 47 seasons of
            blindsides, alliances, and immunity idols, in interactive data.
          </p>
          <span className="tribal-cta">Enter Tribal →</span>
        </div>
        <div className="card-agent-badge tribal-agent">gemini-3-pro / subagent-fire</div>
      </div>
    </a>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// CARD 5: PLANTGURU — Retro NASA mission control
// CRT phosphor green, sensor bars, floating data packets, scanlines
// ══════════════════════════════════════════════════════════════════════════════

function renderPlantGuruCard() {
  return (
    <a href="https://plantguru-fydp.github.io/PlantGuru/" target="_blank" rel="noopener noreferrer" className="card-link">
      <div className="card-nasa">
        <div className="nasa-scanlines" />
        <div className="nasa-vignette" />
        <div className="nasa-grid-bg" />
        <div className="nasa-packets">
          <span className="nasa-packet">0xF4::SOIL_PH=6.8::OK</span>
          <span className="nasa-packet">TX&gt; moisture_delta=+0.3</span>
          <span className="nasa-packet">RX&lt; CLOUD::SCHEDULE_ACK</span>
          <span className="nasa-packet">0xA1::TEMP_C=22.4::NOM</span>
          <span className="nasa-packet">PREDICT::WATER_IN_36H</span>
        </div>
        <div className="nasa-dashboard">
          <div className="nasa-topbar">
            <span className="nasa-mission">◆ PlantGuru Mission Control</span>
            <span className="nasa-clock">SYS.UPTIME 847:23:01</span>
          </div>
          <div className="nasa-main">
            <div className="nasa-titlepanel">
              <h2 className="nasa-title">Plant<br/>Guru</h2>
              <p className="nasa-subtitle">
                IoT-powered botanical intelligence. Cloud-predicted watering schedules.
                Sensor-verified vibes. UWaterloo Capstone.
                <span className="nasa-blink"> █</span>
              </p>
            </div>
            <div className="nasa-sensors">
              <div className="nasa-sensor">
                <span>MOISTURE</span>
                <div className="nasa-bar"><div className="nasa-bar-fill" style={{ width: '78%' }} /></div>
                <span className="nasa-val">78%</span>
              </div>
              <div className="nasa-sensor">
                <span>SUNLIGHT</span>
                <div className="nasa-bar"><div className="nasa-bar-fill" style={{ width: '92%' }} /></div>
                <span className="nasa-val">92%</span>
              </div>
              <div className="nasa-sensor">
                <span>TEMP °C</span>
                <div className="nasa-bar"><div className="nasa-bar-fill" style={{ width: '64%' }} /></div>
                <span className="nasa-val">22.4</span>
              </div>
              <div className="nasa-sensor">
                <span>HUMIDITY</span>
                <div className="nasa-bar"><div className="nasa-bar-fill" style={{ width: '55%' }} /></div>
                <span className="nasa-val">55%</span>
              </div>
              <div className="nasa-sensor">
                <span>SOIL pH</span>
                <div className="nasa-bar"><div className="nasa-bar-fill" style={{ width: '70%' }} /></div>
                <span className="nasa-val">6.8</span>
              </div>
            </div>
          </div>
          <div className="nasa-statusbar">
            <div className="nasa-status-badge">
              <span className="nasa-status-dot" />
              PLANT STATUS: THRIVING
            </div>
            <span className="nasa-cta">
              ACCESS DASHBOARD <span className="nasa-cta-blink">▸</span>
            </span>
          </div>
        </div>
        <div className="card-agent-badge nasa-agent">gemini-3-pro / subagent-mission-ctrl</div>
      </div>
    </a>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
// MAIN PAGE STYLES
// ══════════════════════════════════════════════════════════════════════════════

const mainStyles = `
  @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@400;500;600&family=Share+Tech+Mono&family=Orbitron:wght@400;700;900&family=Caveat:wght@400;700&display=swap');

  .projects-room *, .projects-room *::before, .projects-room *::after {
    margin: 0; padding: 0; box-sizing: border-box;
  }
  .projects-room {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    background: #fafafa;
    color: #111827;
    min-height: 100vh;
    overflow-x: hidden;
    -webkit-font-smoothing: antialiased;
  }

  .card-link { text-decoration: none; display: block; }

  /* ── NAV ── */
  .proj-nav {
    position: fixed; top: 0; left: 0; right: 0; z-index: 100;
    padding: 20px 40px;
    display: flex; justify-content: space-between; align-items: center;
    background: rgba(250,250,250,0.85);
    backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px);
    border-bottom: 1px solid #eee;
  }
  .proj-nav-link {
    font-family: 'Space Grotesk', sans-serif; font-size: 14px; font-weight: 500;
    color: #6b7280; text-decoration: none; letter-spacing: 0.02em;
    transition: color 0.2s; cursor: pointer; background: none; border: none;
  }
  .proj-nav-link:hover { color: #111827; }
  .proj-nav-link.active { color: #111827; font-weight: 600; }
  .proj-nav-right { display: flex; gap: 24px; }

  /* ── HERO ── */
  .proj-hero {
    padding: 160px 40px 40px; max-width: 900px; margin: 0 auto;
    opacity: 0; transform: translateY(30px);
    animation: projFadeUp 0.8s ease forwards 0.1s;
  }
  .proj-hero-label {
    font-family: 'Space Grotesk', sans-serif;
    font-size: 13px; font-weight: 600; text-transform: uppercase;
    letter-spacing: 0.12em; color: #6366f1; margin-bottom: 20px;
  }
  .proj-hero-title {
    font-family: 'Space Grotesk', sans-serif;
    font-size: clamp(40px, 6vw, 72px); font-weight: 700; line-height: 1;
    letter-spacing: -0.03em; color: #0a0a0a; margin-bottom: 20px;
  }
  .proj-hero-subtitle {
    font-size: 18px; line-height: 1.6; color: #6b7280; max-width: 560px;
  }
  .proj-gemini-tag {
    font-family: 'Share Tech Mono', monospace;
    font-size: 14px; color: #10b981;
    background: rgba(16,185,129,0.08); padding: 2px 8px;
    border-radius: 4px; border: 1px solid rgba(16,185,129,0.2);
  }

  /* ── GALLERY ── */
  .proj-gallery {
    max-width: 900px; margin: 0 auto;
    padding: 40px 40px 80px;
    display: flex; flex-direction: column; gap: 32px;
  }

  /* ── AGENT BADGE ── */
  .card-agent-badge {
    position: absolute; bottom: 10px; right: 12px;
    font-family: 'Share Tech Mono', monospace;
    font-size: 9px; letter-spacing: 0.08em; text-transform: uppercase;
    color: rgba(255,255,255,0.25); z-index: 10;
    padding: 3px 8px; border-radius: 3px;
    background: rgba(0,0,0,0.2); backdrop-filter: blur(4px);
  }

  /* ── FOOTER ── */
  .proj-footer {
    max-width: 900px; margin: 0 auto; padding: 60px 40px 80px;
    display: flex; justify-content: space-between; align-items: center;
    border-top: 1px solid #eee;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.7s;
  }
  .proj-footer-link {
    font-family: 'Space Grotesk', sans-serif; font-size: 15px; font-weight: 500;
    color: #6b7280; text-decoration: none; cursor: pointer;
    background: none; border: none; transition: color 0.2s;
    display: inline-flex; align-items: center; gap: 8px;
  }
  .proj-footer-link:hover { color: #111827; }

  @keyframes projFadeUp {
    from { opacity: 0; transform: translateY(30px); }
    to { opacity: 1; transform: translateY(0); }
  }

  @media (max-width: 700px) {
    .proj-hero { padding: 140px 20px 30px; }
    .proj-gallery { padding: 30px 20px 60px; }
    .proj-nav { padding: 16px 20px; }
    .proj-footer { padding: 40px 20px 60px; flex-direction: column; gap: 20px; }
  }
`;

// ══════════════════════════════════════════════════════════════════════════════
// CARD STYLES — Each card is a completely different universe
// ══════════════════════════════════════════════════════════════════════════════

const cardStyles = `
  /* ═══════════════════════════════════════
     CARD 1: INFINITE LEVELS — Chalkboard
     Green slate, chalk dust, handwritten math
     ═══════════════════════════════════════ */
  .card-chalk {
    position: relative; width: 100%; min-height: 380px;
    background: #2d4a3e;
    background-image:
      linear-gradient(135deg, #1e3a2f 0%, #2d4a3e 30%, #345545 60%, #2a4238 100%);
    border-radius: 4px; padding: 40px 36px; overflow: hidden;
    font-family: 'Caveat', 'Patrick Hand', cursive;
    color: rgba(255,255,255,0.85);
    box-shadow:
      0 8px 40px rgba(0,0,0,0.3),
      inset 0 0 100px rgba(0,0,0,0.15),
      inset 0 2px 0 rgba(255,255,255,0.03);
    border: 8px solid #5c3d2e;
    border-image: linear-gradient(180deg, #7a5a45, #4a2f1e, #6b4c38) 1;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.2s;
  }
  .card-chalk:hover {
    transform: translateY(-4px);
    box-shadow: 0 16px 60px rgba(0,0,0,0.4), inset 0 0 100px rgba(0,0,0,0.15);
  }
  .chalk-dust {
    position: absolute; inset: 0;
    background:
      radial-gradient(ellipse 40% 30% at 20% 80%, rgba(255,255,255,0.04) 0%, transparent 70%),
      radial-gradient(ellipse 30% 20% at 70% 20%, rgba(255,255,255,0.03) 0%, transparent 60%),
      radial-gradient(ellipse 50% 40% at 50% 60%, rgba(255,255,255,0.02) 0%, transparent 70%);
    pointer-events: none;
  }
  .chalk-grid {
    position: absolute; inset: 0; opacity: 0.04;
    background:
      repeating-linear-gradient(0deg, transparent 0px, transparent 38px, rgba(255,255,255,0.5) 38px, rgba(255,255,255,0.5) 39px),
      repeating-linear-gradient(90deg, transparent 0px, transparent 38px, rgba(255,255,255,0.3) 38px, rgba(255,255,255,0.3) 39px);
    pointer-events: none;
  }
  .chalk-recursion {
    position: absolute; right: 30px; top: 30px; z-index: 2;
  }
  .chalk-box {
    border: 1.5px solid rgba(255,255,255,0.3); padding: 8px;
    animation: chalkPulse 3s ease-in-out infinite;
  }
  .chalk-box:nth-child(1) { animation-delay: 0s; }
  .chalk-box .chalk-box { animation-delay: 0.4s; }
  .chalk-box .chalk-box .chalk-box { animation-delay: 0.8s; }
  @keyframes chalkPulse {
    0%, 100% { border-color: rgba(255,255,255,0.2); transform: rotate(0deg); }
    50% { border-color: rgba(255,255,255,0.5); transform: rotate(2deg); }
  }
  .chalk-box-inner {
    width: 12px; height: 12px; background: rgba(255,255,255,0.3);
    animation: chalkPulse 3s ease-in-out infinite 1.2s;
  }
  .chalk-equations {
    position: absolute; inset: 0; pointer-events: none; z-index: 1;
  }
  .chalk-eq {
    position: absolute; font-size: 18px; color: rgba(255,255,255,0.12);
    font-family: 'Caveat', cursive; font-style: italic;
  }
  .eq1 { top: 15%; left: 60%; transform: rotate(-3deg); font-size: 22px; }
  .eq2 { top: 35%; left: 65%; transform: rotate(2deg); }
  .eq3 { top: 55%; right: 15%; transform: rotate(-5deg); font-size: 16px; }
  .eq4 { top: 10%; left: 35%; transform: rotate(4deg); font-size: 14px; }
  .eq5 { top: 70%; left: 60%; transform: rotate(-2deg); font-size: 15px; }
  .chalk-content { position: relative; z-index: 3; margin-top: 20px; }
  .chalk-subtitle {
    font-size: 13px; color: rgba(255,255,255,0.4);
    letter-spacing: 4px; text-transform: uppercase; margin-bottom: 8px;
    font-family: 'Share Tech Mono', monospace;
  }
  .chalk-title {
    font-family: 'Caveat', cursive;
    font-size: 52px; font-weight: 700; color: rgba(255,255,255,0.9);
    line-height: 1.1; margin-bottom: 12px;
    text-shadow: 1px 1px 0 rgba(0,0,0,0.3);
  }
  .chalk-desc {
    font-family: 'Inter', sans-serif; font-size: 15px; line-height: 1.7;
    color: rgba(255,255,255,0.55); max-width: 420px; margin-bottom: 24px;
    font-style: normal;
  }
  .chalk-cta {
    display: inline-block; padding: 10px 28px;
    background: transparent; border: 2px solid rgba(255,255,255,0.4);
    color: rgba(255,255,255,0.8);
    font-family: 'Share Tech Mono', monospace; font-size: 13px;
    letter-spacing: 2px; text-transform: uppercase;
    cursor: pointer; transition: all 0.3s ease;
  }
  .card-chalk:hover .chalk-cta {
    background: rgba(255,255,255,0.15); border-color: rgba(255,255,255,0.6);
    color: #fff;
  }

  /* ═══════════════════════════════════════
     CARD 2: FOUR NINES — Retro CRT terminal
     ═══════════════════════════════════════ */
  .card-crt {
    position: relative; width: 100%; min-height: 380px;
    background: #1a1a1a; border-radius: 0; overflow: hidden;
    font-family: 'Courier New', monospace;
    border: 3px solid #2a2a2a;
    box-shadow: inset 0 0 60px rgba(0,0,0,0.8), 0 8px 40px rgba(0,0,0,0.3);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.3s;
  }
  .card-crt:hover {
    transform: translateY(-4px);
    box-shadow: inset 0 0 60px rgba(0,0,0,0.8), 0 16px 60px rgba(0,0,0,0.4),
      0 0 40px rgba(76,175,80,0.1);
  }
  .crt-scanlines {
    position: absolute; inset: 0; z-index: 8; pointer-events: none;
    background: repeating-linear-gradient(
      0deg, rgba(0,255,0,0.03) 0px, rgba(0,255,0,0.03) 1px, transparent 1px, transparent 3px
    );
  }
  .crt-vignette {
    position: absolute; inset: 0; z-index: 7; pointer-events: none;
    background: radial-gradient(ellipse at center, transparent 60%, rgba(0,0,0,0.4) 100%);
  }
  .crt-screen {
    background: linear-gradient(180deg, #0d1a0d 0%, #0a0f0a 100%);
    margin: 16px; padding: 28px 24px; border: 2px solid #333; border-radius: 4px;
    position: relative; overflow: hidden; min-height: 300px;
  }
  .crt-screen::before {
    content: ''; position: absolute; top: 0; left: 0; right: 0; bottom: 0;
    background: repeating-linear-gradient(
      0deg, rgba(0,255,0,0.03) 0px, rgba(0,255,0,0.03) 1px, transparent 1px, transparent 3px
    );
    pointer-events: none; z-index: 1;
  }
  .crt-screen::after {
    content: ''; position: absolute; top: 0; left: 0; right: 0; bottom: 0;
    background: radial-gradient(ellipse at center, transparent 60%, rgba(0,0,0,0.4) 100%);
    pointer-events: none; z-index: 1;
  }
  .crt-header {
    display: flex; justify-content: space-between; align-items: flex-start;
    margin-bottom: 20px; position: relative; z-index: 2;
  }
  .crt-digits { display: flex; gap: 8px; }
  .crt-digit {
    font-size: 48px; font-weight: 900; color: #ff5722; line-height: 1;
    text-shadow: 0 0 10px rgba(255,87,34,0.8), 0 0 30px rgba(255,87,34,0.4), 0 0 60px rgba(255,87,34,0.2);
    animation: crtFlicker 3s ease-in-out infinite;
  }
  .crt-digit:nth-child(2) { animation-delay: 0.5s; }
  .crt-digit:nth-child(3) { animation-delay: 1s; }
  .crt-digit:nth-child(4) { animation-delay: 1.5s; }
  @keyframes crtFlicker {
    0%,100% { opacity: 1; } 90% { opacity: 1; } 92% { opacity: 0.8; }
    94% { opacity: 1; } 96% { opacity: 0.9; } 98% { opacity: 1; }
  }
  .crt-equations {
    font-size: 12px; color: #4caf50; text-align: right; opacity: 0.7;
    line-height: 1.4; font-family: 'Courier New', monospace;
  }
  .crt-title {
    font-size: 24px; font-weight: 700; color: #4caf50;
    text-shadow: 0 0 8px rgba(76,175,80,0.6); letter-spacing: 2px;
    margin-bottom: 6px; position: relative; z-index: 2; text-transform: uppercase;
  }
  .crt-cursor { display: inline-block; animation: crtBlink 1s step-end infinite; color: #4caf50; }
  @keyframes crtBlink { 0%,100% { opacity: 1; } 50% { opacity: 0; } }
  .crt-version {
    font-size: 11px; color: #666; letter-spacing: 3px; text-transform: uppercase;
    margin-bottom: 20px; position: relative; z-index: 2;
  }
  .crt-desc {
    font-size: 14px; line-height: 1.7; color: #33cc33;
    position: relative; z-index: 2; margin-bottom: 24px; opacity: 0.85;
  }
  .crt-prompt { color: #666; margin-right: 8px; }
  .crt-cta {
    position: relative; z-index: 2; display: inline-block; padding: 10px 28px;
    background: #ff5722; border: none; color: #1a1a1a;
    font-family: 'Courier New', monospace; font-size: 13px; font-weight: 900;
    letter-spacing: 2px; text-transform: uppercase; cursor: pointer; transition: all 0.2s;
  }
  .card-crt:hover .crt-cta {
    background: #ff7043; box-shadow: 0 0 30px rgba(255,87,34,0.7); transform: translateY(-1px);
  }
  .crt-statusbar {
    display: flex; justify-content: space-between; background: #111;
    padding: 6px 16px; font-size: 10px; color: #555;
    border-top: 1px solid #222;
  }
  .crt-dot {
    display: inline-block; width: 6px; height: 6px; border-radius: 50%;
    background: #ff5722; box-shadow: 0 0 6px rgba(255,87,34,0.6);
    margin-right: 6px; animation: crtDotPulse 2s ease-in-out infinite;
  }
  @keyframes crtDotPulse { 0%,100% { opacity: 1; } 50% { opacity: 0.4; } }
  .crt-agent { color: rgba(76,175,80,0.3); background: rgba(0,20,0,0.5); }

  /* ═══════════════════════════════════════
     CARD 3: MATCH FIVE — Swiss minimalist
     Massive whitespace, Helvetica, hairline rules
     ═══════════════════════════════════════ */
  .card-swiss {
    position: relative; width: 100%; min-height: 360px;
    background: #ffffff; border-radius: 0; overflow: hidden;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    border: 1px solid #e0e0e0;
    box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.4s;
  }
  .card-swiss:hover {
    transform: translateY(-4px);
    box-shadow: 0 12px 40px rgba(0,0,0,0.08);
  }
  .swiss-rule {
    position: absolute; left: 0; right: 0; height: 1px; background: #e0e0e0;
  }
  .swiss-rule-top { top: 60px; }
  .swiss-rule-mid { top: 50%; }
  .swiss-grid {
    display: grid; grid-template-columns: 200px 1fr;
    height: 100%; min-height: 360px;
  }
  .swiss-col { padding: 80px 36px 36px; }
  .swiss-col-left {
    border-right: 1px solid #e0e0e0;
    display: flex; flex-direction: column;
    align-items: center; justify-content: center; gap: 32px;
    background: #fafafa;
  }
  .swiss-num {
    font-family: 'Helvetica Neue', Helvetica, sans-serif;
    font-size: 96px; font-weight: 100; color: #e0e0e0;
    line-height: 1; letter-spacing: -4px;
  }
  .swiss-tiles {
    display: flex; gap: 6px;
  }
  .swiss-tile {
    width: 32px; height: 32px; background: #111; color: #fff;
    display: flex; align-items: center; justify-content: center;
    font-size: 16px; font-weight: 700; letter-spacing: 0;
  }
  .swiss-col-right {
    display: flex; flex-direction: column; justify-content: center;
  }
  .swiss-category {
    font-size: 10px; font-weight: 600; letter-spacing: 0.2em;
    text-transform: uppercase; color: #999; margin-bottom: 16px;
  }
  .swiss-title {
    font-family: 'Helvetica Neue', Helvetica, sans-serif;
    font-size: 56px; font-weight: 900; color: #111;
    line-height: 1; letter-spacing: -2px; margin-bottom: 20px;
  }
  .swiss-desc {
    font-size: 15px; line-height: 1.7; color: #666; max-width: 380px; margin-bottom: 28px;
  }
  .swiss-cta {
    display: inline-block; padding: 12px 32px;
    background: #111; color: #fff;
    font-size: 13px; font-weight: 600; letter-spacing: 0.1em;
    text-transform: uppercase; cursor: pointer; transition: all 0.2s;
    border: none;
  }
  .card-swiss:hover .swiss-cta {
    background: #333;
  }
  .swiss-footer {
    position: absolute; bottom: 0; left: 0; right: 0;
    display: flex; gap: 16px; padding: 12px 36px;
    font-size: 10px; font-weight: 600; letter-spacing: 0.15em;
    text-transform: uppercase; color: #ccc; border-top: 1px solid #e0e0e0;
  }
  .swiss-agent { color: rgba(0,0,0,0.2); background: rgba(0,0,0,0.03); }

  /* ═══════════════════════════════════════
     CARD 4: SURVIVOR STATS — Tribal council
     Fire gradient, rising embers, torch glow
     ═══════════════════════════════════════ */
  .card-tribal {
    position: relative; width: 100%; min-height: 420px;
    background: #0a0400; overflow: hidden;
    font-family: 'Georgia', serif; border: none; border-radius: 0;
    transition: transform 0.3s ease;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.5s;
  }
  .card-tribal:hover { transform: translateY(-4px); }
  .tribal-fire {
    position: absolute; inset: 0;
    background: linear-gradient(
      0deg, #0a0400 0%, #1a0800 15%, #3d1200 35%,
      #8b2500 55%, #E65100 75%, #ff8f00 90%, #ffcc02 100%
    );
    background-size: 100% 300%;
    animation: tribalFireRise 4s ease-in-out infinite alternate;
  }
  @keyframes tribalFireRise {
    0% { background-position: 0% 60%; } 50% { background-position: 0% 55%; }
    100% { background-position: 0% 65%; }
  }
  .tribal-embers { position: absolute; inset: 0; overflow: hidden; pointer-events: none; }
  .tribal-ember {
    position: absolute; width: 3px; height: 3px; background: #ffcc02;
    border-radius: 50%; box-shadow: 0 0 6px 2px rgba(255,140,0,0.8);
    animation: tribalEmberRise 3s ease-out infinite; opacity: 0;
  }
  .tribal-ember:nth-child(1) { left: 8%; animation-delay: 0s; animation-duration: 3.2s; }
  .tribal-ember:nth-child(2) { left: 18%; animation-delay: 0.4s; animation-duration: 2.8s; }
  .tribal-ember:nth-child(3) { left: 28%; animation-delay: 0.9s; animation-duration: 3.5s; }
  .tribal-ember:nth-child(4) { left: 38%; animation-delay: 0.2s; animation-duration: 2.6s; }
  .tribal-ember:nth-child(5) { left: 48%; animation-delay: 0.7s; animation-duration: 3.0s; }
  .tribal-ember:nth-child(6) { left: 58%; animation-delay: 1.2s; animation-duration: 3.3s; }
  .tribal-ember:nth-child(7) { left: 68%; animation-delay: 1.6s; animation-duration: 2.9s; }
  .tribal-ember:nth-child(8) { left: 78%; animation-delay: 0.5s; animation-duration: 3.1s; }
  .tribal-ember:nth-child(9) { left: 88%; animation-delay: 1.4s; animation-duration: 2.7s; }
  .tribal-ember:nth-child(10) { left: 15%; animation-delay: 1.8s; animation-duration: 3.4s; }
  .tribal-ember:nth-child(11) { left: 45%; animation-delay: 0.1s; animation-duration: 2.5s; }
  .tribal-ember:nth-child(12) { left: 72%; animation-delay: 1.0s; animation-duration: 3.6s; }
  .tribal-ember:nth-child(13) { left: 33%; animation-delay: 0.6s; animation-duration: 2.8s; }
  .tribal-ember:nth-child(14) { left: 92%; animation-delay: 1.3s; animation-duration: 3.1s; }
  @keyframes tribalEmberRise {
    0% { bottom: -5%; opacity: 0; transform: translateX(0) scale(1); }
    10% { opacity: 1; } 60% { opacity: 0.8; }
    100% { bottom: 105%; opacity: 0; transform: translateX(20px) scale(0.3); }
  }
  .tribal-torches { position: absolute; inset: 0; pointer-events: none; }
  .tribal-torches::before {
    content: ''; position: absolute; left: 3%; top: 10%; width: 80px; height: 200px;
    background: radial-gradient(ellipse at center, rgba(255,140,0,0.25) 0%, transparent 70%);
    animation: tribalTorch 1.5s ease-in-out infinite alternate;
  }
  .tribal-torches::after {
    content: ''; position: absolute; right: 3%; top: 10%; width: 80px; height: 200px;
    background: radial-gradient(ellipse at center, rgba(255,140,0,0.25) 0%, transparent 70%);
    animation: tribalTorch 1.5s ease-in-out infinite alternate-reverse;
  }
  @keyframes tribalTorch {
    0% { opacity: 0.6; transform: scaleY(1); } 33% { opacity: 1; transform: scaleY(1.05); }
    66% { opacity: 0.75; transform: scaleY(0.97); } 100% { opacity: 0.9; transform: scaleY(1.02); }
  }
  .tribal-pattern {
    position: absolute; inset: 0; opacity: 0.08; pointer-events: none;
    background:
      repeating-linear-gradient(0deg, transparent 0px, transparent 24px, rgba(255,200,100,0.6) 24px, rgba(255,200,100,0.6) 26px),
      repeating-linear-gradient(60deg, transparent 0px, transparent 30px, rgba(255,150,50,0.4) 30px, rgba(255,150,50,0.4) 32px),
      repeating-linear-gradient(-60deg, transparent 0px, transparent 30px, rgba(255,150,50,0.3) 30px, rgba(255,150,50,0.3) 32px);
  }
  .tribal-smoke {
    position: absolute; top: 0; left: 0; right: 0; height: 60%;
    background: linear-gradient(to bottom, rgba(10,4,0,0.4) 0%, transparent 100%);
    pointer-events: none; z-index: 1;
  }
  .tribal-vote {
    position: absolute; top: 20px; right: 20px;
    width: 90px; height: 120px;
    background: linear-gradient(160deg, #f5e6c8, #e8d5a8, #d4c090);
    border-radius: 2px; box-shadow: 2px 3px 12px rgba(0,0,0,0.5);
    transform: rotate(5deg);
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    animation: tribalVoteHover 3s ease-in-out infinite; z-index: 2;
  }
  .tribal-vote::before {
    content: ''; position: absolute; inset: 4px;
    border: 1px solid rgba(139,37,0,0.2); border-radius: 1px;
  }
  .tribal-vote-label {
    font-family: 'Georgia', serif; font-size: 10px;
    color: rgba(139,37,0,0.5); text-transform: uppercase; letter-spacing: 2px; margin-bottom: 4px;
  }
  .tribal-vote-name {
    font-family: 'Brush Script MT', 'Segoe Script', cursive;
    font-size: 22px; color: #3d1200; transform: rotate(-3deg);
  }
  @keyframes tribalVoteHover {
    0%,100% { transform: rotate(5deg) translateY(0); }
    50% { transform: rotate(3deg) translateY(-5px); }
  }
  .tribal-stats {
    position: absolute; top: 20px; left: 20px;
    display: flex; flex-direction: column; gap: 8px; z-index: 2;
  }
  .tribal-stat {
    background: rgba(10,4,0,0.7); backdrop-filter: blur(8px);
    border: 1px solid rgba(255,140,0,0.3); border-radius: 4px;
    padding: 6px 12px; display: flex; align-items: baseline; gap: 6px;
  }
  .tribal-stat-num {
    font-family: 'Courier New', monospace; font-size: 18px; font-weight: 900;
    color: #ffcc02; text-shadow: 0 0 8px rgba(255,204,2,0.5);
  }
  .tribal-stat-label {
    font-family: 'Georgia', serif; font-size: 10px;
    color: rgba(255,200,150,0.6); text-transform: uppercase; letter-spacing: 1px;
  }
  .tribal-content {
    position: absolute; bottom: 0; left: 0; right: 0; padding: 32px;
    background: linear-gradient(to top, rgba(10,4,0,0.98) 0%, rgba(10,4,0,0.8) 50%, transparent 100%);
    z-index: 2;
  }
  .tribal-divider {
    width: 60px; height: 2px;
    background: linear-gradient(90deg, transparent, #ff8f00, transparent);
    margin-bottom: 12px; animation: tribalDivPulse 2s ease-in-out infinite alternate;
  }
  @keyframes tribalDivPulse { 0% { opacity: 0.5; width: 60px; } 100% { opacity: 1; width: 80px; } }
  .tribal-eyebrow {
    font-family: 'Courier New', monospace; font-size: 10px; text-transform: uppercase;
    letter-spacing: 4px; color: rgba(255,140,0,0.6); margin-bottom: 6px; display: block;
  }
  .tribal-title {
    font-family: 'Georgia', serif; font-size: 34px; font-weight: 700;
    color: #ffcc02; text-shadow: 0 0 20px rgba(255,204,2,0.4), 0 2px 4px rgba(0,0,0,0.5);
    letter-spacing: 1px; margin-bottom: 8px; line-height: 1.1;
  }
  .tribal-desc {
    font-family: 'Georgia', serif; font-size: 14px;
    color: rgba(255,200,150,0.75); font-style: italic; line-height: 1.6;
    margin-bottom: 20px; max-width: 450px;
  }
  .tribal-cta {
    display: inline-block; padding: 12px 28px;
    background: linear-gradient(135deg, #E65100, #ff8f00);
    color: #fff; font-family: 'Georgia', serif; font-size: 14px; font-weight: 700;
    text-transform: uppercase; letter-spacing: 2px; cursor: pointer; border: none;
    transition: all 0.3s ease;
    clip-path: polygon(0 0, calc(100% - 12px) 0, 100% 12px, 100% 100%, 12px 100%, 0 calc(100% - 12px));
  }
  .card-tribal:hover .tribal-cta {
    background: linear-gradient(135deg, #bf360c, #E65100);
    box-shadow: 0 0 30px rgba(230,81,0,0.5); transform: translateY(-2px);
  }
  .tribal-agent { color: rgba(255,200,100,0.25); background: rgba(0,0,0,0.4); }

  /* ═══════════════════════════════════════
     CARD 5: PLANTGURU — NASA Mission Control
     CRT phosphor green, sensor readouts, floating packets
     ═══════════════════════════════════════ */
  .card-nasa {
    position: relative; width: 100%; height: 400px;
    overflow: hidden; background: #030a01;
    border: 1px solid #0f3d0c;
    box-shadow: 0 0 30px rgba(46,125,50,0.15), inset 0 0 80px rgba(0,20,0,0.5);
    font-family: 'Share Tech Mono', monospace;
    transition: transform 0.3s ease, box-shadow 0.4s ease;
    opacity: 0; animation: projFadeUp 0.6s ease forwards 0.6s;
  }
  .card-nasa:hover {
    transform: translateY(-4px);
    box-shadow: 0 0 60px rgba(46,125,50,0.3), 0 0 120px rgba(46,125,50,0.1),
      inset 0 0 80px rgba(0,20,0,0.5);
  }
  .nasa-scanlines {
    position: absolute; inset: 0; z-index: 10; pointer-events: none;
    background: repeating-linear-gradient(
      0deg, transparent 0px, transparent 2px, rgba(0,255,0,0.015) 2px, rgba(0,255,0,0.015) 4px
    );
    animation: nasaScanroll 8s linear infinite;
  }
  @keyframes nasaScanroll { from { background-position: 0 0; } to { background-position: 0 100px; } }
  .nasa-vignette {
    position: absolute; inset: 0; z-index: 9; pointer-events: none;
    background: radial-gradient(ellipse 70% 60% at 50% 50%, transparent 0%, rgba(0,0,0,0.6) 100%);
  }
  .card-nasa::before {
    content: ''; position: absolute; inset: 0;
    background: rgba(0,255,0,0.01); animation: nasaFlicker 0.15s infinite alternate;
    pointer-events: none; z-index: 8;
  }
  @keyframes nasaFlicker { 0% { opacity: 1; } 50% { opacity: 0.97; } 100% { opacity: 1; } }
  .nasa-grid-bg {
    position: absolute; inset: 0;
    background: linear-gradient(rgba(0,255,0,0.03) 1px, transparent 1px),
      linear-gradient(90deg, rgba(0,255,0,0.03) 1px, transparent 1px);
    background-size: 24px 24px;
    animation: nasaGridPulse 4s ease-in-out infinite;
  }
  @keyframes nasaGridPulse { 0%,100% { opacity: 0.4; } 50% { opacity: 0.8; } }
  .nasa-dashboard {
    position: relative; z-index: 5;
    display: grid; grid-template-columns: 1fr 1fr; grid-template-rows: auto 1fr auto;
    height: 100%; padding: 20px; gap: 12px;
  }
  .nasa-topbar {
    grid-column: 1 / -1; display: flex; justify-content: space-between; align-items: center;
    border-bottom: 1px solid rgba(0,255,0,0.15); padding-bottom: 10px;
  }
  .nasa-mission {
    font-family: 'Orbitron', monospace; font-size: 10px; font-weight: 700;
    letter-spacing: 0.25em; text-transform: uppercase; color: #4caf50;
    animation: nasaTextGlow 2s ease-in-out infinite alternate;
  }
  @keyframes nasaTextGlow {
    from { text-shadow: 0 0 4px rgba(76,175,80,0.5); }
    to { text-shadow: 0 0 12px rgba(76,175,80,0.8), 0 0 30px rgba(76,175,80,0.3); }
  }
  .nasa-clock { font-size: 11px; color: rgba(0,255,0,0.5); letter-spacing: 0.1em; }
  .nasa-main { grid-column: 1 / -1; display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
  .nasa-titlepanel { display: flex; flex-direction: column; justify-content: center; gap: 12px; }
  .nasa-title {
    font-family: 'Orbitron', monospace; font-size: clamp(28px, 4vw, 42px);
    font-weight: 900; color: #4caf50; line-height: 1.1;
    text-shadow: 0 0 20px rgba(76,175,80,0.6), 0 0 60px rgba(76,175,80,0.2);
    letter-spacing: 0.05em;
  }
  .nasa-subtitle {
    font-size: 12px; color: rgba(0,255,0,0.6); line-height: 1.6; max-width: 320px;
  }
  .nasa-blink { animation: nasaBlink 1s step-end infinite; }
  @keyframes nasaBlink { 0%,100% { opacity: 1; } 50% { opacity: 0; } }
  .nasa-sensors {
    display: flex; flex-direction: column; gap: 8px; justify-content: center;
    border-left: 1px solid rgba(0,255,0,0.08); padding-left: 16px;
  }
  .nasa-sensor {
    display: flex; justify-content: space-between; align-items: center;
    font-size: 11px; color: rgba(0,255,0,0.45); letter-spacing: 0.05em;
  }
  .nasa-val {
    font-family: 'Orbitron', monospace; font-weight: 700; font-size: 13px;
    color: #4caf50; text-shadow: 0 0 6px rgba(76,175,80,0.5);
  }
  .nasa-bar {
    flex: 1; height: 3px; margin: 0 10px; background: rgba(0,255,0,0.08);
    border-radius: 2px; overflow: hidden; position: relative;
  }
  .nasa-bar-fill {
    position: absolute; top: 0; left: 0; height: 100%;
    background: linear-gradient(90deg, #1b5e20, #4caf50);
    box-shadow: 0 0 6px rgba(76,175,80,0.4); border-radius: 2px;
  }
  .nasa-statusbar {
    grid-column: 1 / -1; display: flex; justify-content: space-between; align-items: center;
    border-top: 1px solid rgba(0,255,0,0.15); padding-top: 12px;
  }
  .nasa-status-badge {
    display: inline-flex; align-items: center; gap: 8px;
    font-family: 'Orbitron', monospace; font-size: 11px; font-weight: 700;
    letter-spacing: 0.15em; text-transform: uppercase; color: #4caf50;
    padding: 6px 14px; border: 1px solid rgba(76,175,80,0.3); background: rgba(76,175,80,0.05);
  }
  .nasa-status-dot {
    width: 6px; height: 6px; border-radius: 50%; background: #4caf50;
    box-shadow: 0 0 8px rgba(76,175,80,0.8); animation: nasaPulse 2s ease-in-out infinite;
  }
  @keyframes nasaPulse { 0%,100% { opacity: 1; transform: scale(1); } 50% { opacity: 0.4; transform: scale(0.7); } }
  .nasa-cta {
    display: inline-flex; align-items: center; gap: 8px;
    font-family: 'Share Tech Mono', monospace; font-size: 12px; color: #4caf50;
    padding: 8px 20px; border: 1px solid rgba(76,175,80,0.4);
    background: rgba(76,175,80,0.08); letter-spacing: 0.1em;
    text-transform: uppercase; transition: all 0.3s ease; cursor: pointer;
  }
  .card-nasa:hover .nasa-cta {
    background: rgba(76,175,80,0.2); border-color: #4caf50;
    box-shadow: 0 0 20px rgba(76,175,80,0.3); color: #81c784;
  }
  .nasa-cta-blink { animation: nasaBlink 1.2s step-end infinite; }
  .nasa-packets {
    position: absolute; inset: 0; pointer-events: none; z-index: 2; overflow: hidden;
  }
  .nasa-packet {
    position: absolute; font-family: 'Share Tech Mono', monospace;
    font-size: 9px; color: rgba(0,255,0,0.12); white-space: nowrap;
    animation: nasaFloat 12s linear infinite;
  }
  .nasa-packet:nth-child(1) { left: 5%; top: 20%; animation-delay: 0s; animation-duration: 14s; }
  .nasa-packet:nth-child(2) { left: 25%; top: 40%; animation-delay: -3s; animation-duration: 11s; }
  .nasa-packet:nth-child(3) { left: 55%; top: 15%; animation-delay: -7s; animation-duration: 16s; }
  .nasa-packet:nth-child(4) { left: 75%; top: 55%; animation-delay: -2s; animation-duration: 13s; }
  .nasa-packet:nth-child(5) { left: 40%; top: 70%; animation-delay: -9s; animation-duration: 15s; }
  @keyframes nasaFloat {
    0% { transform: translateY(0) translateX(0); opacity: 0; }
    10% { opacity: 0.12; } 90% { opacity: 0.12; }
    100% { transform: translateY(-200px) translateX(30px); opacity: 0; }
  }
  .nasa-agent { color: rgba(76,175,80,0.25); background: rgba(0,20,0,0.5); }

  /* ── Responsive ── */
  @media (max-width: 700px) {
    .swiss-grid { grid-template-columns: 1fr; }
    .swiss-col-left { border-right: none; border-bottom: 1px solid #e0e0e0; padding: 40px 36px 24px; }
    .swiss-num { font-size: 64px; }
    .swiss-title { font-size: 40px; }
    .nasa-main { grid-template-columns: 1fr; }
    .nasa-sensors { border-left: none; border-top: 1px solid rgba(0,255,0,0.08); padding-left: 0; padding-top: 12px; }
    .nasa-title { font-size: 28px; }
    .chalk-title { font-size: 36px; }
    .card-chalk { padding: 30px 24px; }
  }
`;

export default ProjectsRoom;
