import { SiteActivity } from '../../hooks/useSiteActivity';

/* ──────────────────────────────────────────────────────────────────────
   Josh Toast Messages — terminal-style toast notifications that look
   like messages from Josh himself. Parallel to the chatbot popup
   system but with a developer/terminal aesthetic.
   ────────────────────────────────────────────────────────────────────── */

export interface JoshToastMessage {
  id: string;
  text: string;
  /** Priority: higher = shown first */
  priority: number;
  /** How long to show the toast in ms */
  duration?: number;
  /** Only show once per session */
  once?: boolean;
  /** Which pages this toast can appear on (empty = all) */
  pages?: string[];
  /** Condition to check */
  condition: (activity: SiteActivity) => boolean;
}

export const JOSH_TOAST_MESSAGES: JoshToastMessage[] = [
  // ── LOBBY ─────────────────────────────────────────────────────────
  {
    id: 'josh-lobby-welcome',
    text: "ok, I think it's working now. take a look around.",
    priority: 100,
    once: true,
    pages: ['lobby'],
    condition: (a) => a.currentPage === 'lobby' && a.timeOnPage === 3 && a.navCount <= 2,
  },
  {
    id: 'josh-lobby-return',
    text: "welcome back. i added some stuff since last time.",
    priority: 95,
    once: true,
    pages: ['lobby'],
    condition: (a) => a.isReturnVisitor && a.currentPage === 'lobby' && a.timeOnPage === 2,
  },
  {
    id: 'josh-lobby-idle',
    text: "you can click on the sticky note or the projects folder btw",
    priority: 30,
    once: true,
    pages: ['lobby'],
    condition: (a) => a.currentPage === 'lobby' && a.timeOnPage > 25 && a.navCount <= 1,
  },

  // ── ABOUT PAGE ────────────────────────────────────────────────────
  {
    id: 'josh-about-hint',
    text: "that 'add to cart' button looks clickable...",
    priority: 80,
    once: true,
    pages: ['about'],
    duration: 6000,
    condition: (a) => a.currentPage === 'about' && a.timeOnPage >= 8 && !a.clickedAddToCart,
  },
  {
    id: 'josh-about-table',
    text: "i promise the comparison table is completely objective and not biased at all",
    priority: 50,
    once: true,
    pages: ['about'],
    condition: (a) => a.currentPage === 'about' && a.timeOnPage === 5,
  },
  {
    id: 'josh-about-long',
    text: "you're really studying this huh. i'm flattered",
    priority: 40,
    once: true,
    pages: ['about'],
    condition: (a) => a.currentPage === 'about' && a.timeOnPage > 40,
  },

  // ── PROJECTS PAGE ─────────────────────────────────────────────────
  {
    id: 'josh-projects-enter',
    text: "each card was generated by a different AI agent. i take no responsibility for their taste.",
    priority: 70,
    once: true,
    pages: ['projects'],
    condition: (a) => a.currentPage === 'projects' && a.timeOnPage === 3,
  },
  {
    id: 'josh-projects-browse',
    text: "the Infinite Levels one is my favorite. spent way too many weekends on it",
    priority: 45,
    once: true,
    pages: ['projects'],
    condition: (a) => a.currentPage === 'projects' && a.timeOnPage > 20,
  },
  {
    id: 'josh-projects-long',
    text: "if you actually play Four Nines, trying making 73 with four 9s. it's brutal.",
    priority: 35,
    once: true,
    pages: ['projects'],
    condition: (a) => a.currentPage === 'projects' && a.timeOnPage > 45,
  },

  // ── HIDDEN PAGES ──────────────────────────────────────────────────
  {
    id: 'josh-void',
    text: "ah, you found the void. yeah. i made this at 2am.",
    priority: 85,
    once: true,
    pages: ['void'],
    condition: (a) => a.currentPage === 'void' && a.timeOnPage === 2,
  },
  {
    id: 'josh-debug',
    text: "welcome to debug mode. try not to break anything... actually go ahead.",
    priority: 85,
    once: true,
    pages: ['debug'],
    condition: (a) => a.currentPage === 'debug' && a.timeOnPage === 2,
  },
  {
    id: 'josh-hamburger',
    text: "yes my last name is actually hamburger. yes i've heard every joke.",
    priority: 85,
    once: true,
    pages: ['hamburger'],
    condition: (a) => a.currentPage === 'hamburger' && a.timeOnPage === 2,
  },

  // ── TIME-BASED ────────────────────────────────────────────────────
  {
    id: 'josh-late-night',
    text: "you're up late. respect. i'm probably also up right now debugging something.",
    priority: 60,
    once: true,
    condition: (a) => a.hour >= 1 && a.hour < 5 && a.totalTime > 10,
  },
  {
    id: 'josh-morning',
    text: "morning. coffee's brewing. the site's been up all night.",
    priority: 50,
    once: true,
    condition: (a) => a.hour >= 6 && a.hour < 9 && a.totalTime > 5,
  },

  // ── MILESTONE ─────────────────────────────────────────────────────
  {
    id: 'josh-five-min',
    text: "you've been here 5 minutes. i appreciate the thoroughness.",
    priority: 35,
    once: true,
    condition: (a) => a.totalTime >= 300,
  },
  {
    id: 'josh-explorer',
    text: "you've checked out everything. not many people do that. thanks for exploring.",
    priority: 75,
    once: true,
    condition: (a) => a.uniquePages.has('about') && a.uniquePages.has('projects') && a.uniquePages.has('lobby') && a.totalTime > 60,
  },
];

/**
 * Get the best matching Josh toast message for the current state.
 */
export function getNextJoshToast(
  activity: SiteActivity,
  shownMessages: Set<string>
): JoshToastMessage | null {
  const candidates = JOSH_TOAST_MESSAGES
    .filter(msg => {
      if (msg.once && shownMessages.has(msg.id)) return false;
      if (msg.pages && msg.pages.length > 0 && !msg.pages.includes(activity.currentPage)) return false;
      try { return msg.condition(activity); } catch { return false; }
    })
    .sort((a, b) => b.priority - a.priority);

  return candidates[0] || null;
}
